#
# Sample configuration file for PlayerInvites
#

## Allow a player to buy invites:
buyInvite: false

## Set price per invite:
buyInvitePrice: 5000

## Commands
cmdBase: "invite"
cmdUse: "use"
cmdGive: "give"
cmdShow: "show"
cmdReload: "reload"
cmdBuy: "buy"
cmdHelp: "help"

## Language settings
stringUsage: "Usage:"
stringPlayer: "player"
stringAmount: "amount"
stringHelpShow: "Show player invites"
stringHelpShowYour: "Show your invites"
stringHelpUse: "Use invite on player"
stringHelpBuy: "Buy invites"
stringHelpBuyCost: "One invite costs %s"
stringHelpGive: "Gives a player invites"

stringInvitesNone: "%s has no invites available"
stringInvitesSelfNone: "You have no invites available"
stringInvitesOne: "%s has one invite available"
stringInvitesSelfOne: "You have one invite available"
stringInvites: "%s has %d invites available"
stringInvitesSelf: "You have %d invites available"
stringInvitedBy: "%s was invited by %p"
stringInvited: "%s has invited:"
stringAnd: "and"
stringInvitedNone: "%s hasn't invited anyone yet"
stringInviteGiven: "You have been given %d additional invite(s)."
stringInviteGivenUsage: "Invite new players with /invite <player>"
stringGiveInvite: "%s has been given %d new invite(s)."
stringInviteSuccess: "%s has been invited."
stringNoInvites: "You have no invites available"
stringInviteError: "Unable to invite %s"
stringInviteExists: "%s has already been invited"
stringPermissionError: "You don't have permission for that command"
stringNoPlayer: "No player specified"
stringPlayerNotFound: "Player %s was not found"
stringBuyDisabled: "Buying invites is disabled"
stringBuySuccess: "Bought %d invites for %s"
stringBuyFailed: "You don't have enough money to buy %d invites, another %s is needed"
stringBuyError: "Unable to withdraw money"