##
## Sample configuration file for PlayerInvites
##
## Enable to allow users to buy invites for in-game money
## Requires the Vault plugin (and any of its supported Economy plugins)
##
buyInvite: false
##
## Price per invite
##
buyInvitePrice: 5000

##
## Number of players to show in toplists
##
topInvites: 5
topInvited: 5

##
## Periodically give players invites
##
auto:
  all:
    ## Interval (in minutes, 10080 = 1 week)
    #interval: 10080
    ## Don't automatically give any invites to players that
    ## has x invites already.
    #max: 5
    ## Give all players 2 invites once (normally the first time
    ## they join the server)
    #once: 0
  vip:
    ## Example:
    ## Give all players with permission "invites.auto.vip" 2 new invites once a week
    ## And one invite once the first time they join/get vip
    ## Don't give any invites if they have 10 or more invites already
    interval: 10080
    interval_count: 2
    max: 10
    once: 1

##
## Commands
## Uncomment the variables below to change name of the commands
## Note that in order to change "base" you must create an alias
## for that command to /invite
##
#cmdBase: "invite"
#cmdUse: "use"
#cmdGive: "give"
#cmdShow: "show"
#cmdReload: "reload"
#cmdBuy: "buy"
#cmdHelp: "help"
#cmdStats: "stats"
#cmdTop: "top"
