name: PlayerInvites
main: se.bonan.playerinvites.PlayerInvites
version: 0.2
author: bonaan
commands:
  invite:
    description: Handles invitations, see /invite help
    usage: /invite help
    permission: invites.use
permissions:
  invites.use:
    description: Can use /invite
    default: true
  invites.invite:
    description: Allows a player to use invites
    default: true
  invites.show:
    description: Allows a player to see its invite count and invited players
    default: true
  invites.showother:
    description: Allows a player to see other players invite count and invited players
    default: op
  invites.buy:
    description: Allows a player to buy invites
    default: true
  invites.give:
    description: Allows a player to give away invites
    default: op
  invites.showgiven:
    description: Displays a message to a user when they're given invites
    default: true
  invites.reload:
    description: Reload invites configuration and data files
    default: op
  invites.auto:
    description: Give player invites automatically
    default: true
  invites.auto.*:
    description: See config.yml for explaination
    default: false